.TH flexiblas_print_avail_backends  3 "Mar. 2017" "M. Koehler" "The FlexiBLAS Library" 
.SH NAME
flexiblas_print_avail_backends \- prints the available FlexiBLAS backends to a file. 

.SH SYNOPSIS
\fB#include <flexiblas/flexiblas_api.h>

\fBvoid flexiblas_print_avail_backends(FILE *\fIfp\fB);\fR

Link with \fI-lflexiblas\fR. 

.SH DESCRIPTION
\fBflexiblas_print_avail_backends\fR prints the list of currently available FlexiBLAS backends
to the file addressed by \fIfp\fR. The standard output \fIstdout\fR can also be used as file.

.SH RETURN VALUE
None.

.SH ERRORS
No errors occur. 

.SH REPORTING BUGS
The current information about the developers and reporting bugs can be found on the FlexiBLAS homepage. 

FlexiBLAS Homepage: <http://www.mpi-magdeburg.mpg.de/projects/flexiblas>

.SH AUTHORS 
 Martin Koehler, Jens Saak 

.SH COPYRIGHT
Copyright (C) 2013, 2014, 2015, 2016, 2017 Martin Koehler, Jens Saak. 
.SH LICENSE
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

