.TH flexiblas_set_num_threads  3 "2013-2025" "M. Koehler" "The FlexiBLAS Library"
.SH NAME
flexiblas_set_num_threads \- set the number of threads the backend should use for computation.

.SH SYNOPSIS
\fB#include <flexiblas/flexiblas_api.h>

\fBvoid flexiblas_set_num_threads(int \fInum\fB);\fR

and as weak aliases

\fBvoid openblas_set_num_threads(int \fInum\fB);\fR
.br
\fBvoid mkl_set_num_threads(int \fInum\fB);\fR
.br
\fBvoid blas_set_num_threads(int \fInum\fB);\fR
.br
\fBvoid acmlsetnumthreads(int \fInum\fB);\fR
.br

Link with \fI-lflexiblas\fR.

.SH DESCRIPTION
\fBflexiblas_set_num_threads\fR function changes the number of threads used for computation if
the backend supports this. The aliases exist for compatibility reasons with other BLAS implementations
like Intel MKL, OpenBLAS, or AMD ACML.

.SH ERRORS

No errors occur.

.SH REPORTING BUGS
The current information about the developers and reporting bugs can be found on the FlexiBLAS homepage.

FlexiBLAS Homepage: <http://www.mpi-magdeburg.mpg.de/projects/flexiblas>

.SH AUTHORS
 Martin Koehler, Jens Saak

.SH COPYRIGHT
Copyright (C) 2013-2025 Martin Koehler
.SH LICENSE
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

