.TH flexiblas_print_current_backend  3 "2013-2025" "M. Koehler" "The FlexiBLAS Library"
.SH NAME
flexiblas_print_current_backend \- prints the currently loead/active backend to a file.

.SH SYNOPSIS
\fB#include <flexiblas/flexiblas_api.h>

\fBvoid flexiblas_print_current_backend(FILE *\fIfp\fB);\fR

Link with \fI-lflexiblas\fR.

.SH DESCRIPTION
\fBflexiblas_print_current_backend\fR prints the currently loaded/active FlexiBLAS backend
to the file addressed by \fIfp\fR. The standard output \fIstdout\fR can also be used as file.

.SH RETURN VALUE
None.

.SH ERRORS
No errors occur.

.SH REPORTING BUGS
The current information about the developers and reporting bugs can be found on the FlexiBLAS homepage.

FlexiBLAS Homepage: <http://www.mpi-magdeburg.mpg.de/projects/flexiblas>

.SH SEE ALSO
.BR flexiblas_current_backend (3)
.SH AUTHORS
 Martin Koehler, Jens Saak

.SH COPYRIGHT
Copyright (C) 2013-2025 Martin Koehler
.SH LICENSE
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

