.TH flexiblas_current_backend  3 "2013-2025" "M. Koehler" "The FlexiBLAS Library"
.SH NAME
flexiblas_current_backend \- return the name of the currently used backend.

.SH SYNOPSIS
\fB#include <flexiblas/flexiblas_api.h>

\fBint flexiblas_current_backend(char * \fIname\fB, size_t *\fIlen\fB );\fR

Link with \fI-lflexiblas\fR.

.SH DESCRIPTION
\fBflexiblas_current_backend\fR copies the name of the currently loaded backend to the
buffer addressed by \fIname\fR of length \fIlen\fR. If the name is longer than the buffer
on the first \fIlen-1\fR characters are copied.


.SH RETURN VALUE
On success, the length of the backend's name determined by \fBstrlen\fR.

.SH ERRORS

No errors occur.

.SH SEE ALSO
.BR flexiblas_list_loaded (3),
.BR flexiblas_list (3),
.BR flexiblas_print_current_backend (3)

.SH REPORTING BUGS
The current information about the developers and reporting bugs can be found on the FlexiBLAS homepage.

FlexiBLAS Homepage: <http://www.mpi-magdeburg.mpg.de/projects/flexiblas>

.SH AUTHORS
 Martin Koehler, Jens Saak

.SH COPYRIGHT
Copyright (C) 2013-2025 Martin Koehler
.SH LICENSE
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

