.TH flexiblas_get_version  3 "2013-2022" "M. Koehler" "The FlexiBLAS Library"
.SH NAME
flexiblas_get_version \- retrieve the used FlexiBLAS version.
.SH SYNOPSIS
\fB#include <flexiblas/flexiblas_api.h>

\fBvoid flexiblas_get_version(int *\fImajor\fB, int *\fIminor\fB, int *\fIpatchlevel\fB);

Link with \fI-lflexiblas\fR.

.SH DESCRIPTION
\fBflexiblas_get_version\fR returns the version of the used FlexiBLAS library
as triple \fImajor\fR.\fIminor\fR.\fIpatchlevel\fR.

.SH RETURN VALUE
None.

.SH ERRORS
No errors occur.

.SH REPORTING BUGS
The current information about the developers and reporting bugs can be found on the FlexiBLAS homepage.

FlexiBLAS Homepage: <http://www.mpi-magdeburg.mpg.de/projects/flexiblas>

.SH AUTHORS
 Martin Koehler, Jens Saak

.SH COPYRIGHT
Copyright (C) 2013-2022 Martin Koehler
.SH LICENSE
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

