#!/bin/sh
set -e

update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas64.so.3 \
	                    libblas64.so.3-x86_64-linux-gnu \
			                        /usr/lib/x86_64-linux-gnu/libflexiblas64.so.3 120

update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack64.so.3 \
	                    liblapack64.so.3-x86_64-linux-gnu \
			                        /usr/lib/x86_64-linux-gnu/libflexiblas64.so.3 120

#DEBHELPER#

exit 0


