#! /bin/sh
#!/bin/sh
set -e

update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so \
	libblas.so-x86_64-linux-gnu \
	/usr/lib/x86_64-linux-gnu/libflexiblas.so \
	120 \
	--slave /usr/include/x86_64-linux-gnu/cblas.h \
	cblas.h-x86_64-linux-gnu \
	/usr/include/flexiblas/cblas.h \
	--slave /usr/lib/x86_64-linux-gnu/pkgconfig/blas.pc \
	blas.pc-x86_64-linux-gnu \
	/usr/lib/x86_64-linux-gnu/pkgconfig/flexiblas.pc

update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so \
	liblapack.so-x86_64-linux-gnu \
	/usr/lib/x86_64-linux-gnu/libflexiblas.so \
	120 \
	--slave /usr/lib/x86_64-linux-gnu/pkgconfig/lapack.pc \
	lapack.pc-x86_64-linux-gnu \
	/usr/lib/x86_64-linux-gnu/pkgconfig/flexiblas.pc


#DEBHELPER#

exit 0


