MODULE CSC_SYSINFO
    USE ISO_C_BINDING
    IMPLICIT NONE

    INTERFACE
        FUNCTION CSC_SYSINFO_GETPID_C() BIND(C,name="csc_sysinfo_getpid")
            IMPORT
            INTEGER(KIND=C_INT) :: CSC_SYSINFO_GETPID_C
        END FUNCTION CSC_SYSINFO_GETPID_C

    END INTERFACE

CONTAINS
    INTEGER FUNCTION CSC_SYSINFO_GETPID()
        IMPLICIT NONE
        INTEGER(KIND=C_INT) :: RETC
        INTEGER :: RET

        RETC = CSC_SYSINFO_GETPID_C()
        RET = INT(RETC)
        CSC_SYSINFO_GETPID = RET
    END FUNCTION


END MODULE

