INCLUDE(CheckFortranFunctionExists)

MACRO(CHECKLAPACKROUTINE ROUTINE VAR_TO_SET)
    SET(_X ${CMAKE_REQUIRED_LIBRARIES})
    SET(CMAKE_REQUIRED_LIBRARIES ${LAPACK_LIBRARIES} ${BLAS_LIBRARIES})

    CHECK_FORTRAN_FUNCTION_EXISTS(${ROUTINE} ${VAR_TO_SET})
    SET(CMAKE_REQUIRED_LIBRARIES ${_X})
ENDMACRO()

