#ifndef FLEXIBLAS_DUMMY_CBLAS_H
#define FLEXIBLAS_DUMMY_CBLAS_H



#ifdef __cplusplus
extern "C" { 
#endif

/*-----------------------------------------------------------------------------
 *  CBLAS Interface 
 *-----------------------------------------------------------------------------*/
void cblas_caxpy();
void cblas_ccopy();
void cblas_cdotc_sub();
void cblas_cdotu_sub();
void cblas_cgbmv();
void cblas_cgemm();
void cblas_cgemv();
void cblas_cgerc();
void cblas_cgeru();
void cblas_chbmv();
void cblas_chemm();
void cblas_chemv();
void cblas_cher2();
void cblas_cher2k();
void cblas_cher();
void cblas_cherk();
void cblas_chpmv();
void cblas_chpr2();
void cblas_chpr();
void cblas_cscal();
void cblas_csscal();
void cblas_cswap();
void cblas_csymm();
void cblas_csyr2k();
void cblas_csyrk();
void cblas_ctbmv();
void cblas_ctbsv();
void cblas_ctpmv();
void cblas_ctpsv();
void cblas_ctrmm();
void cblas_ctrmv();
void cblas_ctrsm();
void cblas_ctrsv();
void cblas_dasum();
void cblas_daxpy();
void cblas_dcopy();
void cblas_ddot();
void cblas_dgbmv();
void cblas_dgemm();
void cblas_dgemv();
void cblas_dger();
void cblas_dnrm2();
void cblas_drot();
void cblas_drotg();
void cblas_drotm();
void cblas_drotmg();
void cblas_dsbmv();
void cblas_dscal();
void cblas_dsdot();
void cblas_dspmv();
void cblas_dspr2();
void cblas_dspr();
void cblas_dswap();
void cblas_dsymm();
void cblas_dsymv();
void cblas_dsyr2();
void cblas_dsyr2k();
void cblas_dsyr();
void cblas_dsyrk();
void cblas_dtbmv();
void cblas_dtbsv();
void cblas_dtpmv();
void cblas_dtpsv();
void cblas_dtrmm();
void cblas_dtrmv();
void cblas_dtrsm();
void cblas_dtrsv();
void cblas_dzasum();
void cblas_dznrm2();
void cblas_icamax();
void cblas_idamax();
void cblas_isamax();
void cblas_izamax();
void cblas_sasum();
void cblas_saxpy();
void cblas_scasum();
void cblas_scnrm2();
void cblas_scopy();
void cblas_sdot();
void cblas_sdsdot();
void cblas_sgbmv();
void cblas_sgemm();
void cblas_sgemv();
void cblas_sger();
void cblas_snrm2();
void cblas_srot();
void cblas_srotg();
void cblas_srotm();
void cblas_srotmg();
void cblas_ssbmv();
void cblas_sscal();
void cblas_sspmv();
void cblas_sspr2();
void cblas_sspr();
void cblas_sswap();
void cblas_ssymm();
void cblas_ssymv();
void cblas_ssyr2();
void cblas_ssyr2k();
void cblas_ssyr();
void cblas_ssyrk();
void cblas_stbmv();
void cblas_stbsv();
void cblas_stpmv();
void cblas_stpsv();
void cblas_strmm();
void cblas_strmv();
void cblas_strsm();
void cblas_strsv();
void cblas_zaxpy();
void cblas_zcopy();
void cblas_zdotc_sub();
void cblas_zdotu_sub();
void cblas_zdscal();
void cblas_zgbmv();
void cblas_zgemm();
void cblas_zgemv();
void cblas_zgerc();
void cblas_zgeru();
void cblas_zhbmv();
void cblas_zhemm();
void cblas_zhemv();
void cblas_zher2();
void cblas_zher2k();
void cblas_zher();
void cblas_zherk();
void cblas_zhpmv();
void cblas_zhpr2();
void cblas_zhpr();
void cblas_zscal();
void cblas_zswap();
void cblas_zsymm();
void cblas_zsyr2k();
void cblas_zsyrk();
void cblas_ztbmv();
void cblas_ztbsv();
void cblas_ztpmv();
void cblas_ztpsv();
void cblas_ztrmm();
void cblas_ztrmv();
void cblas_ztrsm();
void cblas_ztrsv();

void __flexiblas_dummy_function_to_include_all_cblas_symbols(int dummy){
 	cblas_caxpy();
 	cblas_ccopy();
 	cblas_cdotc_sub();
 	cblas_cdotu_sub();
 	cblas_cgbmv();
 	cblas_cgemm();
 	cblas_cgemv();
 	cblas_cgerc();
 	cblas_cgeru();
 	cblas_chbmv();
 	cblas_chemm();
 	cblas_chemv();
 	cblas_cher2();
 	cblas_cher2k();
 	cblas_cher();
 	cblas_cherk();
 	cblas_chpmv();
 	cblas_chpr2();
 	cblas_chpr();
 	cblas_cscal();
 	cblas_csscal();
 	cblas_cswap();
 	cblas_csymm();
 	cblas_csyr2k();
 	cblas_csyrk();
 	cblas_ctbmv();
 	cblas_ctbsv();
 	cblas_ctpmv();
 	cblas_ctpsv();
 	cblas_ctrmm();
 	cblas_ctrmv();
 	cblas_ctrsm();
 	cblas_ctrsv();
 	cblas_dasum();
 	cblas_daxpy();
 	cblas_dcopy();
 	cblas_ddot();
 	cblas_dgbmv();
 	cblas_dgemm();
 	cblas_dgemv();
 	cblas_dger();
 	cblas_dnrm2();
 	cblas_drot();
 	cblas_drotg();
 	cblas_drotm();
 	cblas_drotmg();
 	cblas_dsbmv();
 	cblas_dscal();
 	cblas_dsdot();
 	cblas_dspmv();
 	cblas_dspr2();
 	cblas_dspr();
 	cblas_dswap();
 	cblas_dsymm();
 	cblas_dsymv();
 	cblas_dsyr2();
 	cblas_dsyr2k();
 	cblas_dsyr();
 	cblas_dsyrk();
 	cblas_dtbmv();
 	cblas_dtbsv();
 	cblas_dtpmv();
 	cblas_dtpsv();
 	cblas_dtrmm();
 	cblas_dtrmv();
 	cblas_dtrsm();
 	cblas_dtrsv();
 	cblas_dzasum();
 	cblas_dznrm2();
 	cblas_icamax();
 	cblas_idamax();
 	cblas_isamax();
 	cblas_izamax();
 	cblas_sasum();
 	cblas_saxpy();
 	cblas_scasum();
 	cblas_scnrm2();
 	cblas_scopy();
 	cblas_sdot();
 	cblas_sdsdot();
 	cblas_sgbmv();
 	cblas_sgemm();
 	cblas_sgemv();
 	cblas_sger();
 	cblas_snrm2();
 	cblas_srot();
 	cblas_srotg();
 	cblas_srotm();
 	cblas_srotmg();
 	cblas_ssbmv();
 	cblas_sscal();
 	cblas_sspmv();
 	cblas_sspr2();
 	cblas_sspr();
 	cblas_sswap();
 	cblas_ssymm();
 	cblas_ssymv();
 	cblas_ssyr2();
 	cblas_ssyr2k();
 	cblas_ssyr();
 	cblas_ssyrk();
 	cblas_stbmv();
 	cblas_stbsv();
 	cblas_stpmv();
 	cblas_stpsv();
 	cblas_strmm();
 	cblas_strmv();
 	cblas_strsm();
 	cblas_strsv();
 	cblas_zaxpy();
 	cblas_zcopy();
 	cblas_zdotc_sub();
 	cblas_zdotu_sub();
 	cblas_zdscal();
 	cblas_zgbmv();
 	cblas_zgemm();
 	cblas_zgemv();
 	cblas_zgerc();
 	cblas_zgeru();
 	cblas_zhbmv();
 	cblas_zhemm();
 	cblas_zhemv();
 	cblas_zher2();
 	cblas_zher2k();
 	cblas_zher();
 	cblas_zherk();
 	cblas_zhpmv();
 	cblas_zhpr2();
 	cblas_zhpr();
 	cblas_zscal();
 	cblas_zswap();
 	cblas_zsymm();
 	cblas_zsyr2k();
 	cblas_zsyrk();
 	cblas_ztbmv();
 	cblas_ztbsv();
 	cblas_ztpmv();
 	cblas_ztpsv();
 	cblas_ztrmm();
 	cblas_ztrmv();
 	cblas_ztrsm();
 	cblas_ztrsv();

}




#ifdef __cplusplus
} 
#endif

#endif /* end of include guard: FLEXIBLAS_DUMMY_CBLAS_H */
