#
# Enable CCache in a build
#

OPTION(USE_CCACHE "Use ccache for compiling" OFF)
IF ( USE_CCACHE STREQUAL ON )
    FIND_PROGRAM(CCACHE_PROGRAM ccache)
    if(CCACHE_PROGRAM)
        MESSAGE(STATUS "Found CCACHE: " ${CCACHE_PROGRAM})
        set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CCACHE_PROGRAM}")
    ENDIF()
ENDIF()

