name: build-mingw
on:
  workflow_dispatch:
  push:
  pull_request:

concurrency: ci-windows-mingw-${{ github.ref }}

jobs:

  mingw:
    # For available GitHub-hosted runners, see:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ${{ matrix.os }}

    name: mingw-w64 (${{ matrix.msystem }})

    defaults:
      run:
        # Use MSYS2 as default shell
        shell: msys2 {0}

    strategy:
      # Allow other runners in the matrix to continue if some fail
      fail-fast: false

      matrix:
        msystem: [UCRT64, CLANG64, CLANGARM64]
        include:
          - msystem: UCRT64
            os: windows-latest
          - msystem: CLANG64
            os: windows-latest
          - msystem: CLANGARM64
            os: windows-11-arm

    steps:
      - name: get runner hardware information
        shell: pwsh
        run : |
          Get-PSDrive -PSProvider FileSystem
          Get-CIMInstance -Class Win32_Processor | Select-Object -Property Name

      - name: install MSYS2 build environment
        uses: msys2/setup-msys2@v2
        with:
          update: true

          # Use pre-installed version if possible to save disc space on
          # partition with source.  We need that space for building.
          release: ${{ matrix.msystem == 'CLANGARM64' }}

          msystem: ${{ matrix.msystem }}

          pacboy: >-
            cc:p
            fc:p
            cmake:p
            ccache:p
            dlfcn:p
            lapack:p
            openblas:p

      - name: checkout repository
        uses: actions/checkout@v5

      - name: prepare ccache
        # create key with human readable timestamp
        # used in action/cache/restore and action/cache/save steps
        id: ccache-prepare
        run: |
          echo "key=ccache:mingw:${{ matrix.os }}:${{ matrix.msystem }}:${{ github.ref }}:$(date +"%Y-%m-%d_%H-%M-%S"):${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "ccachedir=$(cygpath -m $(ccache -k cache_dir))" >> $GITHUB_OUTPUT

      - name: restore ccache
        # setup the GitHub cache used to maintain the ccache from one job to the next
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.ccache-prepare.outputs.ccachedir }}
          key: ${{ steps.ccache-prepare.outputs.key }}
          # Prefer caches from the same branch. Fall back to caches from the dev branch.
          restore-keys: |
            ccache:mingw:${{ matrix.os }}:${{ matrix.msystem }}:${{ github.ref }}:
            ccache:mingw:${{ matrix.os }}:${{ matrix.msystem }}:

      - name: configure ccache
        run: |
          which ccache
          test -d ${{ steps.ccache-prepare.outputs.ccachedir }} || mkdir -p ${{ steps.ccache-prepare.outputs.ccachedir }}
          echo "max_size = 100M" >> ${{ steps.ccache-prepare.outputs.ccachedir }}/ccache.conf
          echo "compression = true" >> ${{ steps.ccache-prepare.outputs.ccachedir }}/ccache.conf
          ccache -p
          ccache -s
          echo "/usr/lib/ccache" >> $GITHUB_PATH

      - name: configure
        run: |
          mkdir ${GITHUB_WORKSPACE}/build
          cd ${GITHUB_WORKSPACE}/build
          cmake \
            -DCMAKE_BUILD_TYPE="Release" \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/usr" \
            -DCMAKE_C_COMPILER_LAUNCHER="ccache" \
            -DCMAKE_Fortran_COMPILER_LAUNCHER="ccache" \
            ..

      - name: build
        run: |
          cd ${GITHUB_WORKSPACE}/build
          cmake --build .

      - name: ccache status
        continue-on-error: true
        run: ccache -s

      - name: save ccache
        # Save the cache after we are done (successfully) building
        # This helps to retain the ccache even if the subsequent steps are failing.
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.ccache-prepare.outputs.ccachedir }}
          key: ${{ steps.ccache-prepare.outputs.key }}

      - name: install
        run: |
          cd ${GITHUB_WORKSPACE}/build
          cmake --install .

      - name: check
        id: run-ctest
        timeout-minutes: 150
        run: |
          cd ${GITHUB_WORKSPACE}/build
          ctest . \
            -j$(nproc) \
            --timeout 300

      - name: Re-run tests
        if: always() && (steps.run-ctest.outcome == 'failure')
        timeout-minutes: 60
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          cd ${GITHUB_WORKSPACE}/build
          echo "::group::Re-run failing tests"
          ctest --rerun-failed --output-on-failure --timeout 180 || true
          echo "::endgroup::"
          echo "::group::Log from these tests"
          [ ! -f Testing/Temporary/LastTest.log ] || cat Testing/Temporary/LastTest.log
          echo "::endgroup::"
